name: 🚀 Deploy to production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Switch to master branch
        uses: actions/checkout@v2
        with:
          ref: master

      - name: 🔼 Transfer via FTP
        uses: wangyucode/sftp-upload-action@v1.4.8
        with:
          host: ${{ secrets.FTP_SERVER }}
          port: ${{ secrets.FTP_PORT }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          remoteDir: ${{ secrets.FTP_PROD_SERVER_DIR }}
          exclude: ".git*"
